INSERT INTO COURSES.COURSE(NAME, START_TIME, END_TIME, LOCATION) 
	VALUES ('LT course', 100, 900, 'Vilnius');
INSERT INTO COURSES.COURSE(NAME, START_TIME, END_TIME, LOCATION) 
	VALUES ('DK course', 200, 1000, 'Copenhagen');
INSERT INTO COURSES.COURSE(NAME, START_TIME, END_TIME, LOCATION) 
	VALUES ('SE course', 600, 700, 'Stockholm');
INSERT INTO COURSES.COURSE(NAME, START_TIME, END_TIME, LOCATION) 
	VALUES ('EN course', 200, 500, 'London');